version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskManagement
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.12.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  authentication:
    build:
      context: ./Authentication
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/taskManagement
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - postgres
      - redis
    ports:
      - "3001:3001"
    restart: always

  task_management:
    build:
      context: ./TaskManagement
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/taskManagement
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - postgres
      - redis
    ports:
      - "3002:3002"
    restart: always

volumes:
  pgdata:
    driver: local